<a href="https://colab.research.google.com/github/panjiram/Program-Tugas-Akhir/blob/main/Crawling_Twitter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install tweepy

Requirement already satisfied: tweepy in /usr/local/lib/python3.7/dist-packages (3.10.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from tweepy) (1.15.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from tweepy) (1.3.0)
Requirement already satisfied: requests[socks]>=2.11.1 in /usr/local/lib/python3.7/dist-packages (from tweepy) (2.23.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->tweepy) (3.1.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy) (2021.10.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy) (3.0.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]>=2.11.1->tweepy) (1.7.1)

In [ ]:
import tweepy # libarary untuk Twitter
import csv    # library untuk membuat file CSV
import urllib.request
import requests as r
import csv
import pandas as pd

In [ ]:
# twitter API access
api_key  = '86JrDrPHwb2FDzQ4BEaE157NK'
api_key_secret = 'FXGTuKw2UF2fnpF7viltXPgd6U7BxgKHhmvJ3JAfGBvWd931ol'
access_token = '865771920-5rj7nkixC6zGp8WE2yeO17hq6bxiu6GCpDj1NP53'
access_token_secret = 'KiqZ9hXaNakVOoVOB0A13frhC0tdz4qaEhPRYdu0Bd107'

In [ ]:
# Autentikasi API Twitter menggunakan Tweepy
auth = tweepy.OAuthHandler(api_key, api_key_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth,wait_on_rate_limit=True)

In [ ]:
message,favorite_count,retweet_count,created_at,user_name,followers_count = [],[],[],[],[],[]

for tweet in tweepy.Cursor(api.search, q="ptm", rpp=10000, count=20, result_type="recent", include_entities=True, lang="id").items(2000):
    message.append(tweet.text)
    favorite_count.append(tweet.favorite_count)
    retweet_count.append(tweet.retweet_count)
    created_at.append(tweet.created_at)
    user_name.append(tweet.user.name)
    followers_count.append(tweet.user.followers_count)
    
list_ = {'Message': message, 
         'Favorite Count' : favorite_count,
         'Retweet Count' :retweet_count,
         'Created At' : created_at,
         'Username' : user_name,
         'Followers' : followers_count}

df = pd.DataFrame(list_)
df.to_csv("ptm.csv") #nama file
df

                                                Message  ...  Followers
0     Gmn ya, alhamdulillah sih paham kalo gua msh b...  ...        935
1     üî• Tadi pas ptm ketemu anak baru, gemess banget...  ...      28986
2     MASHA ALLAH cakep banget üôèüèªüôèüèª btw ini emang bg...  ...        106
3     pls lah yaaa, baru aja mulai ptm https://t.co/...  ...        350
4     Nadiem: Pelaksanaan PTM 100 Persen Menyesuaika...  ...       1824
...                                                 ...  ...        ...
1995  ptm 100% berarti parkiran rame, ada upacara, a...  ...         24
1996  di sekolah saya, ptm nya ganjil genap kayak mo...  ...        270
1997  boleh kok ngeluh capek ptm capek ptm, tp janga...  ...         98
1998  @adhiMID Keprihatinan saya adalah ketidakwaspa...  ...      11493
1999        @jooilysm ohh masi ptm terbatas, semangattü§©  ...       1018

[2000 rows x 6 columns]